### ISSUE TITLE
How to open specific channel

### ISSUE THREAD

**Issue by KaushikTechcronus** [getsocial-im/getsocial-android-sdk#2]
Hello,

I'm using below code to invite.

```
final InviteContent inviteContent = InviteContent.createBuilder()
                .withText("Android")
                .build();
        final LinkParams linkParams = new LinkParams();
        linkParams.put("Android", "Android");

```
```
GetSocial.sendInvite(InviteChannelIds.FACEBOOK_MESSENGER, inviteContent, linkParams, new InviteCallback() {
            @Override
            public void onComplete() {
                Log.e("GetSocial", "Invite was successfully sent.");
            }

            @Override
            public void onCancel() {
                Log.e("GetSocial", "Invite canceled.");
            }

            @Override
            public void onError(Throwable throwable) {
                Log.e("GetSocial", "Error sending invite.");
            }
        });
```

But it will share only link and I want also content to be shared.

Please help me with this.

Thanks

**Comment by yral6012** [comment]
Hi @KaushikTechcronus , Facebook Messenger does not support adding invite content, it essentially builds a rich preview from the url. You can see from the table here which channels support invite content https://docs.getsocial.im/guides/smart-invites/channels/supported-invite-channels/#supported-content-customizations

Also you can customize the content of the landing page that is used to build the rich preview so you can get the desired result.

**Comment by KaushikTechcronus** [comment]
okay thanks
